on:
  push:
    branches:
      - master

jobs:
  my_job:
    name: Release extension
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: |
          npm ci
      - name: VSCE login
        run: |
          # it's a test, this key is no longer valid
          echo 5dtaoga3qd2yhgwduxliaawp2mu56syg4ytbhy6qfedrv2xqexsa | npx vsce login lesha
      - name: VSCE publish
        run: |
          npx vsce publish
