on:
  push:
    branches:
      - master

env:
  VSCE_STORE: ".vsce-store"

jobs:
  my_job:
    name: Release extension
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: |
          npm ci
      - name: Extension packaging
        run: |
          npx vsce package
      - name: Logging in to vsce
        run: |
          echo "${{ secrets.AZURE_TOKEN }}" | npx vsce login ${{ secrets.AZURE_LOGIN }}
      - name: Publish
        run: |
          npx vsce publish
