on:
  push:
    branches:
      - master

jobs:
  my_job:
    name: Release extension
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: |
          npm ci
      - name: VSCE login
        run: |
          echo "${{ secrets.AZURE_TOKEN }}" | npx vsce login ${{ secrets.AZURE_LOGIN }}
      - name: VSCE publish
        run: |
          npx vsce publish
