on:
  push:
    branches:
    - master

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
    steps:
    - name: Install dependencies
      run: |
        npm ci
    - name: VSCE login
      run: |
        echo $AZURE_TOKEN | vsce login $AZURE_LOGIN
    - name: VSCE publish
      run: |
        vsce publish
